### ISSUE TITLE
PDF create doesn't work on ubuntu 22.04

### ISSUE THREAD

**Issue by MakerMark** [hajareshyam/pdf-creator-node#92]
After Updating the Operating System to ubuntu 22.04 the pdf creation doesn't work, it couldn't find a lib named libproviders.so

```
Error: html-pdf: Received the exit code '1'
Auto configuration failed
140346356578240:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140346356578240:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140346356578240:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=providers, path=providers
140346356578240:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=providers

    at ChildProcess.respond (/home/ubuntu/remoteHelipadManagingSystemBE/node_modules/html-pdf/lib/pdf.js:121:31)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

After reading some stackoverflow issue someone suggest to comment the row providers = provider_sect and the exception now is that one

```
Error: html-pdf: Received the exit code '1'
Auto configuration failed
139796807059392:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
139796807059392:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
139796807059392:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
139796807059392:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

    at ChildProcess.respond (/home/ubuntu/remoteHelipadManagingSystemBE/node_modules/html-pdf/lib/pdf.js:121:31)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by Ntwali-Josue** [comment]
Having the same issue on my side too, I am still wondering the solution for this.

**Comment by EduBarrros** [comment]
I had the same problem, I searched but didn't find anything to fix it.

**Comment by ProbablyClem** [comment]
running `export OPENSSL_CONF=/dev/null `
before `npm start` fixed it for me

**Comment by nanjeribrian** [comment]
same to my side

**Comment by nanjeribrian** [comment]
Error: html-pdf: Unknown Error
Auto configuration failed
140143545776064:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140143545776064:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140143545776064:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=providers, path=providers
140143545776064:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=providers

    at ChildProcess.respond (/home/brian/certify/CertifyPdf-Gen/node_modules/html-pdf/lib/pdf.js:134:17)
    at ChildProcess.emit (node:events:513:28)  

   experiencing the same issue to

**Comment by satish2352** [comment]
Hi @all 
Please add in your code 
process.env.OPENSSL_CONF = '/dev/null';

before pdf.create
